export const REQUEST_REPO_PROJECTS = 'REQUEST_REPO_PROJECTS';
export const RECEIVE_REPO_PROJECTS = 'RECEIVE_REPO_PROJECTS';
export const REPO_PROJECTS_REQUEST_FAILED = 'REPO_PROJECTS_REQUEST_FAILED';

export const REQUEST_PROJECT_DETAILS = 'REQUEST_PROJECT_DETAILS';
export const REQUEST_PROJECT_DETAILS_BY_NAME = 'REQUEST_PROJECT_DETAILS_BY_NAME';
export const RECEIVE_PROJECT_DETAILS = 'RECEIVE_PROJECT_DETAILS';
export const PROJECT_DETAILS_REQUEST_FAILED = 'PROJECT_DETAILS_REQUEST_FAILED';

